/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerSach;
import Table.Sach;

/**
 *
 * @author Khanh Vo
 */
public class ViewSach1 extends javax.swing.JPanel {

//    public static void main(String[] args) {
//		try {
//			ViewSach1 vs1 = new ViewSach1();
//			
//			vs1.setVisible(true);
//		} 
//		catch (Exception e) {
//			e.printStackTrace();
//		}
//	}

    /**
     * Creates new form ViewSach1
     */
    
    public ViewSach1() {
        initComponents();
        ControllerSach ctl = new ControllerSach(btnSubmit, btnXoa, jtfMaSach,jtfTenSach,jtfTacGia, jtfGia,jtfSoLuong,jlbMsg,jpnHienThi,jtfTimKiem);   
        ctl.setViewAndEvent();
        
    }

//    public ViewSach1(Sach sach) {
//         initComponents();
//        ControllerSach ctl = new ControllerSach(btnSubmit, btnXoa, jtfMaSach,jtfTenSach,jtfTacGia, jtfGia,jtfSoLuong,jlbMsg,jpnHienThi);   
//        ctl.setViewandEvent(sach);
//    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRoot = new javax.swing.JPanel();
        jpnHienThi = new javax.swing.JPanel();
        jtfMaSach = new javax.swing.JTextField();
        jtfTenSach = new javax.swing.JTextField();
        jtfTacGia = new javax.swing.JTextField();
        jtfGia = new javax.swing.JTextField();
        jtfSoLuong = new javax.swing.JTextField();
        jtfTimKiem = new javax.swing.JTextField();
        jlbMaSach = new javax.swing.JLabel();
        jlbTenSach = new javax.swing.JLabel();
        jlbTacGia = new javax.swing.JLabel();
        jlbGia = new javax.swing.JLabel();
        jlbSoLuong = new javax.swing.JLabel();
        jlbTimKiem = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jlbMsg = new javax.swing.JLabel();

        javax.swing.GroupLayout jpnHienThiLayout = new javax.swing.GroupLayout(jpnHienThi);
        jpnHienThi.setLayout(jpnHienThiLayout);
        jpnHienThiLayout.setHorizontalGroup(
            jpnHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
        );
        jpnHienThiLayout.setVerticalGroup(
            jpnHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jtfTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenSachActionPerformed(evt);
            }
        });

        jtfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTimKiemActionPerformed(evt);
            }
        });

        jlbMaSach.setText("Mã sách");

        jlbTenSach.setText("Tên sách");

        jlbTacGia.setText("Tác giả");

        jlbGia.setText("Giá");

        jlbSoLuong.setText("Số lượng");

        jlbTimKiem.setText("Tìm kiếm");

        btnSubmit.setText("Thêm");

        btnXoa.setText("Xóa");

        jlbMsg.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
        jPanelRoot.setLayout(jPanelRootLayout);
        jPanelRootLayout.setHorizontalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRootLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaSach)
                            .addComponent(jlbTenSach)
                            .addComponent(jlbTacGia))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenSach)
                            .addComponent(jtfTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jtfMaSach))
                        .addGap(150, 150, 150)
                        .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbGia)
                            .addComponent(jlbSoLuong)
                            .addComponent(jlbTimKiem))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfGia)
                            .addComponent(jtfSoLuong)
                            .addComponent(jtfTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(jPanelRootLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRootLayout.createSequentialGroup()
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRootLayout.setVerticalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaSach)
                    .addComponent(jlbGia)
                    .addComponent(jtfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbTenSach)
                        .addComponent(jlbSoLuong))
                    .addComponent(jtfSoLuong))
                .addGap(15, 15, 15)
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbTacGia)
                        .addComponent(jlbTimKiem))
                    .addComponent(jtfTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jpnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTimKiemActionPerformed

    private void jtfTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTenSachActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbMaSach;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JLabel jlbSoLuong;
    private javax.swing.JLabel jlbTacGia;
    private javax.swing.JLabel jlbTenSach;
    private javax.swing.JLabel jlbTimKiem;
    private javax.swing.JPanel jpnHienThi;
    private javax.swing.JTextField jtfGia;
    private javax.swing.JTextField jtfMaSach;
    private javax.swing.JTextField jtfSoLuong;
    private javax.swing.JTextField jtfTacGia;
    private javax.swing.JTextField jtfTenSach;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables


}
